2021-05-29 11:59:45,011 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:45,011 - logger - INFO - There are 1 GPU(s) available.
2021-05-29 11:59:45,013 - logger - INFO - We will use the GPU:Tesla V100-PCIE-32GB
2021-05-29 11:59:45,013 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:45,013 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:45,013 - logger - INFO - [+] System environments
2021-05-29 11:59:45,013 - logger - INFO - The number of gpus : 1
2021-05-29 11:59:45,014 - logger - INFO - The number of cpus : 8
2021-05-29 11:59:45,014 - logger - INFO - Memory Size : 83G
2021-05-29 11:59:45,014 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:45,014 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:45,014 - logger - INFO - initial model
2021-05-29 11:59:45,014 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:46,845 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:46,845 - logger - INFO - [+] Data
2021-05-29 11:59:46,845 - logger - INFO - The number of train samples : 80000
2021-05-29 11:59:46,846 - logger - INFO - The number of validation samples : 20000
2021-05-29 11:59:46,846 - logger - INFO - The number of classes : 245
2021-05-29 11:59:46,846 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:52,629 - logger - INFO - --------------------------------------------------
2021-05-29 11:59:52,629 - logger - INFO - [+] Network
2021-05-29 11:59:52,629 - logger - INFO - Type: Attention
2021-05-29 11:59:52,629 - logger - INFO - Encoder parameters: 44263904
2021-05-29 11:59:52,629 - logger - INFO - Decoder parameters: 539509
2021-05-29 11:59:52,629 - logger - INFO - --------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 509, in <module>
    main(parser.config_file)
  File "train.py", line 356, in main
    train=True,
  File "train.py", line 135, in run_epoch
    output = model(input, expected, train, teacher_forcing_ratio, epoch, ratio_cycle)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/networks/Attention.py", line 320, in forward
    out = self.encoder(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/networks/feature_extractor.py", line 16, in forward
    return self.ConvNet(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/networks/feature_extractor.py", line 133, in forward
    x = self.layer3(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/ml/code/networks/feature_extractor.py", line 40, in forward
    out = self.bn1(out)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 132.00 MiB (GPU 0; 31.72 GiB total capacity; 7.37 GiB already allocated; 38.56 MiB free; 7.41 GiB reserved in total by PyTorch)